-- --------------------------------------------------------
-- Table: CUSTOMER_CONTRACT_ESD
-- --------------------------------------------------------

CREATE TABLE CUSTOMER_CONTRACT_ESD (
    CUST_TYPE VARCHAR2(10 CHAR),
    CUSTOMER VARCHAR2(40 CHAR),
    CUSTOMER_CODE NUMBER,
    CONTRACT_ID VARCHAR2(15 CHAR),
    LABOUR VARCHAR2(15 CHAR),
    MATERIAL VARCHAR2(15 CHAR),
    BILLING_FORM VARCHAR2(15 CHAR),
    FIXED_RATE_COST VARCHAR2(15 CHAR),
    DIP_PROFILE VARCHAR2(15 CHAR)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING;

-- Unique Index for CUSTOMER_CONTRACT_ESD
CREATE UNIQUE INDEX CUSTOMER_CONTRACT_ESD_PK 
ON CUSTOMER_CONTRACT_ESD (CUSTOMER, CUSTOMER_CODE)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS;

-- Primary Key for CUSTOMER_CONTRACT_ESD
ALTER TABLE CUSTOMER_CONTRACT_ESD
ADD CONSTRAINT CUSTOMER_CONTRACT_ESD_PK PRIMARY KEY (CUSTOMER, CUSTOMER_CODE)
USING INDEX CUSTOMER_CONTRACT_ESD_PK
ENABLE;

-- --------------------------------------------------------
-- Table: PN_AUTHORITY_ESD
-- --------------------------------------------------------

CREATE TABLE PN_AUTHORITY_ESD (
    PN VARCHAR2(35 CHAR) NOT NULL ENABLE, 
    AUTHORITY VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    PN_TYPE VARCHAR2(20 CHAR), 
    AUTHORITY_DATE VARCHAR2(12 CHAR), 
    WORKSHOP VARCHAR2(40 CHAR), 
    COMP_CAPABILITY VARCHAR2(40 CHAR), 
    QLTY_STATUS VARCHAR2(40 CHAR), 
    TECH_CONTROL VARCHAR2(20 CHAR), 
    REV_NUMBER NUMBER(2,0), 
    CREATED_BY VARCHAR2(10 BYTE), 
    CREATED_DATE DATE, 
    MODIFIED_BY VARCHAR2(10 CHAR), 
    MODIFIED_DATE DATE, 
    CONSTRAINT PN_AUTHORITY_ESD_PK PRIMARY KEY (PN, AUTHORITY)
    USING INDEX 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

-- Modify REV_NUMBER in PN_AUTHORITY_ESD
ALTER TABLE PN_AUTHORITY_ESD 
MODIFY REV_NUMBER NUMBER(5,0);

-- --------------------------------------------------------
-- Table: ESD_SKILL_MAPPING
-- --------------------------------------------------------

CREATE TABLE ESD_SKILL_MAPPING (
    SKILL_NAME VARCHAR2(1000 BYTE), 
    SKILL VARCHAR2(10 BYTE)
)
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

-- --------------------------------------------------------
-- Table: ZEPARTSER_MASTER
-- --------------------------------------------------------

CREATE TABLE ZEPARTSER_MASTER (
    CUSTOMER VARCHAR2(10 CHAR), 
    PN VARCHAR2(40 CHAR), 
    CREATED_DATE DATE
)
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

-- --------------------------------------------------------
-- Table: WO_ACTUALS_MATERIAL_TEMP
-- --------------------------------------------------------

CREATE TABLE WO_ACTUALS_MATERIAL_TEMP (
    WO_ACTUAL_TRANSACTION VARCHAR2(30),
    TRASACTION_CATEGORY   VARCHAR2(50 CHAR),
    WO                    NUMBER(8),
    GET_PRICE             VARCHAR2(1),
    INVOICED_FLAG         VARCHAR2(1),
    BILLED_PRICE          NUMBER(16, 2),
    CHECKED               VARCHAR2(10 CHAR),
    BILLED_HOURS          NUMBER(16, 2),
    QTY                   NUMBER(8, 2),
    UNIT_COST             NUMBER(18, 4),
    TOTAL_COST            NUMBER(18, 4),
    ADD_BILL_CURRENCY     VARCHAR2(10 CHAR),
    ADD_BILL_CURR_AMOUNT  NUMBER(16, 2),
    UNIT_SELL_B           NUMBER(16, 2),
    VARIANCE_PRICE        NUMBER(16, 2),
    CONSTRAINT PK_WO_ACTUALS_MATERIAL_TEMP PRIMARY KEY (WO_ACTUAL_TRANSACTION, TRASACTION_CATEGORY) ENABLE
);

-- --------------------------------------------------------
-- Table: AUTHORITY_APPROVAL
-- --------------------------------------------------------

CREATE TABLE AUTHORITY_APPROVAL (
    AUTHORITY VARCHAR2(120 CHAR), 
    CODE VARCHAR2(120 CHAR)
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
);

CREATE UNIQUE INDEX AUTHORITY_APPROVAL_PK 
ON AUTHORITY_APPROVAL (AUTHORITY, CODE) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
);

ALTER TABLE AUTHORITY_APPROVAL 
ADD CONSTRAINT AUTHORITY_APPROVAL_PK PRIMARY KEY (AUTHORITY, CODE) 
USING INDEX AUTHORITY_APPROVAL_PK ENABLE;

-- --------------------------------------------------------
-- Table: CONDITION_APPROVAL
-- --------------------------------------------------------

CREATE TABLE CONDITION_APPROVAL (
    CONDITION VARCHAR2(120 CHAR), 
    USER_STATUS VARCHAR2(120 CHAR), 
    CODE VARCHAR2(120 CHAR)
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
);

CREATE UNIQUE INDEX CONDITION_APPROVAL_PK 
ON CONDITION_APPROVAL (CONDITION, USER_STATUS, CODE) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
);

ALTER TABLE CONDITION_APPROVAL 
ADD CONSTRAINT CONDITION_APPROVAL_PK PRIMARY KEY (CONDITION, USER_STATUS, CODE) 
USING INDEX CONDITION_APPROVAL_PK ENABLE;

-- --------------------------------------------------------
-- Table: WO_TASK_CARD_AFTER_WORK
-- --------------------------------------------------------

CREATE TABLE WO_TASK_CARD_AFTER_WORK (
    WO NUMBER(8) NOT NULL,
    TASK_CARD VARCHAR2(35 CHAR) NOT NULL,
    START_DATE DATE
);

-- --------------------------------------------------------
-- Table: ESD_AUTHORITY_MAPPING
-- --------------------------------------------------------

CREATE TABLE ESD_AUTHORITY_MAPPING (
    AUTHORITY_ORIGINAL VARCHAR2(100 CHAR) NOT NULL,
    AUTHORITY_MODIFIED VARCHAR2(8 CHAR) NOT NULL,
    CONSTRAINT PK_ESD_AUTHORITY_MAPPING PRIMARY KEY (AUTHORITY_ORIGINAL, AUTHORITY_MODIFIED)
);

-- --------------------------------------------------------
-- Table: PN_INVENTORY_HISTORY
-- --------------------------------------------------------

ALTER TABLE PN_INVENTORY_HISTORY 
ADD QTY_USED NUMBER(10,2);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD INTERNAL_EXTERNAL VARCHAR2(10 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD REPAIR_SHOPS VARCHAR2(70 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD INTERFACE_TRANSFER_FLAG VARCHAR2(1 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD TRANSACTION VARCHAR2(30);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD MADE_AS_CCS VARCHAR2(1 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD LEGACY_BATCH NUMBER(10);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD STATE_OF_PART VARCHAR2(35 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD INTERFACE_TECO_FLAG VARCHAR2(1 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD SVO_SENT VARCHAR2(1 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD Z_PRINTSTATUS VARCHAR2(1 CHAR);

ALTER TABLE PN_INVENTORY_HISTORY 
ADD INTERFACE_TRANSFER_FLAG_TECO VARCHAR2(1 CHAR);

-- --------------------------------------------------------
-- Table: WO
-- --------------------------------------------------------

ALTER TABLE WO 
ADD INTERFACE_ESD_TRANSFERRED_DATE DATE;

ALTER TABLE WO 
ADD INTERFACE_ESD_TRANSFERRED_FLAG VARCHAR2(1 CHAR);

ALTER TABLE WO 
ADD INTERFACE_TECO_FLAG VARCHAR2(1 CHAR);

ALTER TABLE WO 
ADD INTERFACE_ESD_DATE DATE;

ALTER TABLE WO 
ADD INSPECTION_LOT_NUMBER VARCHAR2(18 CHAR);

ALTER TABLE WO 
ADD CODE VARCHAR2(12 CHAR);

ALTER TABLE WO 
ADD USAGE_DECISION VARCHAR2(1 CHAR);

ALTER TABLE WO 
ADD WORKCENTER VARCHAR2(1 CHAR);

ALTER TABLE WO 
ADD RFO_NO NUMBER(15,0);

ALTER TABLE WO 
ADD OPERATOR VARCHAR2(35 CHAR);

ALTER TABLE WO 
ADD EQUIPMENT VARCHAR2(35 CHAR);

ALTER TABLE WO 
ADD SVO_USED VARCHAR2(1 CHAR);

ALTER TABLE WO 
ADD WORK_CENTER VARCHAR2(10 CHAR); 

ALTER TABLE WO 
ADD INTERFACE_CODE VARCHAR2(1000 CHAR);

ALTER TABLE WO
ADD OUTSTANDING_SAVING_PATH VARCHAR2(4000 CHAR);

ALTER TABLE WO
ADD CP_VISIBLE VARCHAR2(1 CHAR);   

ALTER TABLE WO
ADD INTERFACE_SAP_D_TRANSFER_FLAG  VARCHAR2(1 CHAR);

-- --------------------------------------------------------
-- Table: WO_TASK_CARD
-- --------------------------------------------------------

ALTER TABLE WO_TASK_CARD 
ADD TASK_CARD_DESCRIPTION_OLD VARCHAR2(2000);

ALTER TABLE WO_TASK_CARD 
ADD TASK_CARD_CATEGORY_OLD VARCHAR2(10 CHAR);

ALTER TABLE WO_TASK_CARD 
ADD TASK_CARD_HOURS_OLD VARCHAR2(10 CHAR);

ALTER TABLE WO_TASK_CARD 
ADD STATUS_OLD VARCHAR2(10);

ALTER TABLE WO_TASK_CARD 
ADD INV_CHECK VARCHAR2(1 CHAR);

ALTER TABLE WO_TASK_CARD 
ADD INTERFACE_SAP_TRANSFERRED_DATE DATE;

ALTER TABLE WO_TASK_CARD 
ADD INTERFACE_SAP_TRANSFERRED_FLAG VARCHAR2(10 CHAR);

ALTER TABLE WO_TASK_CARD 
ADD INTERFACE_STEP VARCHAR2(3 CHAR);

ALTER TABLE WO_TASK_CARD 
ADD SVO_SENT VARCHAR2(2 CHAR);

ALTER TABLE WO_TASK_CARD 
ADD INTERFACE_14_TRANSFERRED_FLAG VARCHAR2(10 CHAR);

-- --------------------------------------------------------
-- Table: WO_TASK_CARD_ADUIT
-- --------------------------------------------------------

ALTER TABLE WO_TASK_CARD_ADUIT 
ADD INTERFACE_SAP_TRANSFERRED_DATE DATE;

ALTER TABLE WO_TASK_CARD_ADUIT 
ADD INTERFACE_SAP_TRANSFER_FLAG VARCHAR2(1 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT 
ADD INTERFACE_SAP_TRANSFERRED_FLAG VARCHAR2(10 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT 
ADD TASK_CARD_DESCRIPTION_OLD VARCHAR2(2000);

ALTER TABLE WO_TASK_CARD_ADUIT 
ADD TASK_CARD_CATEGORY_OLD VARCHAR2(10 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT 
ADD TASK_CARD_HOURS_OLD VARCHAR2(10 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT 
ADD STATUS_OLD VARCHAR2(10);

-- --------------------------------------------------------
-- Table: WO_ACTUALS
-- --------------------------------------------------------

ALTER TABLE WO_ACTUALS 
ADD INVOICED_FLAG VARCHAR2(1);

ALTER TABLE WO_ACTUALS 
ADD BILLABLE_HOURS NUMBER(6);

ALTER TABLE WO_ACTUALS 
ADD INTERFACE_ESD_TRANSFERRED_DATE DATE;

ALTER TABLE WO_ACTUALS 
ADD INTERFACE_ESD_TRANSFERRED_FLAG VARCHAR2(1 CHAR);

ALTER TABLE WO_ACTUALS 
ADD GET_PRICE VARCHAR2(1);

ALTER TABLE WO_ACTUALS 
ADD VARIANCE_PRICE NUMBER(16,2);

ALTER TABLE WO_ACTUALS 
ADD INTERFACE_ESD_UP_TRANSFERRED_FLAG VARCHAR2(1 CHAR);

ALTER TABLE WO_ACTUALS 
ADD BILLED_PRICE NUMBER(16,2);

-- --------------------------------------------------------
-- Table: PICKLIST_DISTRIBUTION
-- --------------------------------------------------------

ALTER TABLE PICKLIST_DISTRIBUTION 
ADD EXTERNAL_CUST_TO NUMBER(10);

ALTER TABLE PICKLIST_DISTRIBUTION 
ADD EXTERNAL_CUST_TO_QTY NUMBER(13,2);

ALTER TABLE PICKLIST_DISTRIBUTION 
ADD INTERFACE_ NUMBER(13,2);

-- --------------------------------------------------------
-- Table: REQUISITION_DETAIL
-- --------------------------------------------------------

ALTER TABLE REQUISITION_DETAIL 
ADD PR_NO VARCHAR2(10);

ALTER TABLE REQUISITION_DETAIL 
ADD PR_ITEM NUMBER(5);

ALTER TABLE REQUISITION_DETAIL 
ADD INTERFACE_TRANSFERRED_DATE_ESD DATE;

ALTER TABLE REQUISITION_DETAIL 
ADD RAISE_PR VARCHAR2(1);

-- --------------------------------------------------------
-- Table: REQUISITION_HEADER
-- --------------------------------------------------------

ALTER TABLE REQUISITION_HEADER 
ADD INTERFACE_TRANSFERRED_DATE_ESD DATE;

-- --------------------------------------------------------
-- Table: ORDER_DETAIL
-- --------------------------------------------------------

ALTER TABLE ORDER_DETAIL 
ADD INTERFACE_SYNC_DATE DATE;

ALTER TABLE ORDER_DETAIL 
ADD INTERFACE_SYNC_FLAG VARCHAR2(1 CHAR);

ALTER TABLE ORDER_DETAIL 
ADD EXTERNAL_KPR_NUMBER VARCHAR2(10 CHAR);

ALTER TABLE ORDER_DETAIL 
ADD EXTERNAL_PR_ITEM NUMBER(5);

ALTER TABLE ORDER_DETAIL 
ADD EXTERNAL_RELEASE_STRATEGY VARCHAR2(10 CHAR);

-- --------------------------------------------------------
-- Table: WO_AUDIT
-- --------------------------------------------------------

ALTER TABLE WO_AUDIT 
ADD RFO_NO NUMBER(15,0);

-- --------------------------------------------------------
-- Table: EMPLOYEE_SKILL
-- --------------------------------------------------------

ALTER TABLE EMPLOYEE_SKILL 
ADD PN_TYPE VARCHAR2(20 CHAR);

ALTER TABLE EMPLOYEE_SKILL 
ADD ENGINE VARCHAR2(10 CHAR);

-- --------------------------------------------------------
-- Table: EMPLOYEE_CONTROL
-- --------------------------------------------------------

ALTER TABLE EMPLOYEE_CONTROL 
ADD ENGINE VARCHAR2(10 CHAR);

ALTER TABLE EMPLOYEE_CONTROL 
ADD SKILL VARCHAR2(10);

ALTER TABLE EMPLOYEE_CONTROL 
ADD SKILL_ESD VARCHAR2(10);

-- Modify LICENCE_TYPE in EMPLOYEE_CONTROL
ALTER TABLE EMPLOYEE_CONTROL 
MODIFY LICENCE_TYPE VARCHAR2(20 CHAR);

-- --------------------------------------------------------
-- Table: PICKLIST_DISTRIBUTION_REC
-- --------------------------------------------------------

ALTER TABLE PICKLIST_DISTRIBUTION_REC 
ADD (PICKLIST_BATCH NUMBER(8, 0));

-- --------------------------------------------------------
-- Table: PICKLIST_DISTRIBUTION_REC_AUD
-- --------------------------------------------------------

ALTER TABLE PICKLIST_DISTRIBUTION_REC_AUD 
ADD (PICKLIST_BATCH NUMBER(8, 0));

-- --------------------------------------------------------
--	TECHDOC 2.0 SQLS
-- --------------------------------------------------------

ALTER TABLE INTERFACE_DATA
ADD FILE_NAME VARCHAR2(35 CHAR);

ALTER TABLE WO_TASK_CARD
ADD TD_SVO VARCHAR2(35 CHAR);

ALTER TABLE WO_TASK_CARD
ADD TD_REVISION VARCHAR2(20 CHAR);

ALTER TABLE WO_TASK_CARD
ADD TD_ISSUE_NBR VARCHAR2(20 CHAR);

ALTER TABLE WO_TASK_CARD
ADD TD_ISSUE_DATE VARCHAR2(20 CHAR);

ALTER TABLE WO_TASK_CARD
ADD TD_TRADE_IBL VARCHAR2(20 CHAR);

ALTER TABLE WO
ADD TD_ENGINE_POS VARCHAR2(20 CHAR);

ALTER TABLE WO
ADD TD_APU_SN VARCHAR2(20 CHAR);

--AUDIT

ALTER TABLE WO_TASK_CARD_ADUIT
ADD TD_SVO VARCHAR2(35 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT
ADD TD_REVISION VARCHAR2(20 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT
ADD TD_ISSUE_NBR VARCHAR2(20 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT
ADD TD_ISSUE_DATE VARCHAR2(20 CHAR);

ALTER TABLE WO_TASK_CARD_ADUIT
ADD TD_TRADE_IBL VARCHAR2(20 CHAR);

ALTER TABLE WO_AUDIT
ADD TD_ENGINE_POS VARCHAR2(20 CHAR);

ALTER TABLE WO_AUDIT
ADD TD_APU_SN VARCHAR2(20 CHAR);