//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 11:18:07 AM EDT 
//


package trax.aero.outbound;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;



@XmlRootElement(name="MT_TRAX_RCV_I21_4121_RES", namespace="http://singaporeair.com/mro/ESDTRAX")
@XmlAccessorType(XmlAccessType.FIELD)
public class MT_TRAX_RCV_I21_4121_RES
{
	public String getTrax_repair_order() {
		return Trax_repair_order;
	}

	public String getTrax_repair_order_line() {
		return Trax_repair_order_line;
	}

	public String getKPR_number() {
		return KPR_number;
	}

	public String getPR_item() {
		return PR_item;
	}

	public String getRelease_Strategy() {
		return Release_Strategy;
	}

	public String getMessage_code() {
		return Message_code;
	}

	public String getSuccess_Error_message() {
		return Success_Error_message;
	}

	public void setTrax_repair_order(String trax_repair_order) {
		Trax_repair_order = trax_repair_order;
	}

	public void setTrax_repair_order_line(String trax_repair_order_line) {
		Trax_repair_order_line = trax_repair_order_line;
	}

	public void setKPR_number(String kPR_number) {
		KPR_number = kPR_number;
	}

	public void setPR_item(String pR_item) {
		PR_item = pR_item;
	}

	public void setRelease_Strategy(String release_Strategy) {
		Release_Strategy = release_Strategy;
	}

	public void setMessage_code(String message_code) {
		Message_code = message_code;
	}

	public void setSuccess_Error_message(String success_Error_message) {
		Success_Error_message = success_Error_message;
	}

	@XmlElement(name = "Trax_repair_order")
    private String Trax_repair_order;
	
    @XmlElement(name = "Trax_repair_order_line")
    private String Trax_repair_order_line;
    
    @XmlElement(name = "KPR_number")
    private String KPR_number;
	
    @XmlElement(name = "PR_item")
    private String PR_item;
	
    @XmlElement(name = "Release_Strategy")
    private String Release_Strategy;
	
    @XmlElement(name = "Message_code")
    private String Message_code;
   
    @XmlElement(name = "Success_Error_message")
    private String Success_Error_message;
	
}
