package trax.application_standard_structure;
import trax.TraxObject;
import trax.resources.StPn;
//import trax.controller.TraxController;
//import trax.datawindow.DataWindow;
import trax.types.TraxArrayList;

import java.util.*;



public class st_pn extends TraxObject
{
   private static final long serialVersionUID = 1L;

   public String s_pn = "";
   public String s_dsc;
   public String s_ac_type;
   public String s_ac_series;
   public String s_sn;
   public String s_position;
   public String s_installed_ac;
   public String s_transaction;
   public Integer l_transaction;
   public Integer l_batch;
   public Integer l_wo;
   public Integer l_hours;
   public Integer l_minutes;
   public Double l_cycles;
   public Integer l_days;
   public String s_ac = "";
   public Double l_qty;
   public String s_sos_flag;
   public Integer l_no_of_copies;
   public String s_location;
   public Double  d_qty_available;
   public String s_condition;
   public String s_order_type;
   public List<String> s_pn_nla = new TraxArrayList<String>();
   public List<String> s_sn_nla = new TraxArrayList<String>();
   public Integer l_index;
   public Integer l_control_count;
   public String s_ri;
   public String s_ri_by;
   public Date dt_ri_date;   
   public Date dt_from;
   public Date dt_to;
   public String s_bin;
   public String s_ri_control;
   public Double d_qty_us;
   public Double d_qty_pending_ri;
   public String s_us_code;
   public String s_modified_by;
   public Integer l_notes;
   public Double d_qty_reserved;
   public Date dt_removal_date;
   public Integer l_picklist;
   public Integer l_picklist_line;
   public String s_pn_old;
   public String s_sn_old;
   public Integer l_box_no;
   public Double d_value;
   public String s_pack_ship_flag;
   public Integer l_ship_pack;
   public String s_pack_ship_express;
   public String s_ship_from_location;
   public String s_ship_to_category;
   public String s_ship_to;
   public String s_qty_type;
   public String s_nha_pn;
   public String s_nha_sn;
   public String s_pn_category;
   public Integer l_goods_rcvd_batch;
   public Integer l_order_number;
   public Integer l_order_line;
   public List<Integer> l_picklist_control = new TraxArrayList<Integer>(Integer.class);
   public String s_window_supervisor;
   public String s_message;
   public String s_password_pass;
   public String s_wall_password;
   public String s_category;
   public String s_pn_interchng;
   public String s_vendor;
   public String s_position_description;
   public String s_dd_field;
   public String s_dd_value;
   public String s_pn_nha;
   public String s_old_pn;
   public Date dt_modified_date;
   public Date dt_reset_date;
   public boolean  b_nla;
   public String s_interchangeable_flag;
   public String s_error_flag;
   public String s_build_kit;
   public String s_auto_issued;
   public st_security ms_security;
   public String s_transaction_cat;
   public String s_security;
   public String s_inventory_type;
   public String s_issue_to_employee;
   public String s_issue_to;
   public String s_where;
   public String s_report;
   public String s_ipc;
   public String s_pn_transaction_type;
   public String s_nla_pn;
   public String s_nla_position;
   public String s_owner_omit_flag;
   public String s_nla_import_file;
   public String s_task_card;
   public Date dt_installed_date;
   public Integer l_installed_hour;
   public Integer l_installed_minute;
   public String s_owner;
   public String s_loan_category;
   public String s_zone;
   public Integer l_chap;
   public Integer l_sec;
   public Integer l_par;
   public String s_compare;
   public Double l_qty_picked;
   public String s_calling_window;
   public String s_position_group;
   public String s_remove_as_serviceable;
   public String s_original_ac;
   public String s_prorated_flag;
   public String s_control;
   public String s_status;
   public String s_effectivity;
   public String s_pn_change;
   public Integer l_requisition;
   public Integer l_requisition_line;
   public String s_uom;
   public Date dt_created_date;
   public String s_created_by;
   public Date dt_expire_date;
   public Integer l_do_not_update_pn_inv_control;
   public String s_trn;
   public List<String> s_trn_array = new TraxArrayList<String>();
   public Boolean  b_mobile_picklist_issue;
   public Integer l_picklist_distribution_line;
   public String s_task_card_pn;
   public String s_task_card_sn;
   public String s_to_bin;
   public String s_employee;
   public String s_skill;
   public Integer l_traxdoc_row_id;
   public String s_file_name_path;
   public List<String> s_pn_multi = new TraxArrayList<String>();
   public List<String> s_sn_multi = new TraxArrayList<String>();
   //public DataWindow dw;
   public String s_form;
   public Boolean  b_auto_receiving;
   public String s_pn_restricted;
   public String s_gl_company;
   public String s_gl_expenditure;
   public String s_gl;
   public String s_gl_cost_center;
   public Integer l_so_number;
   public Integer l_reset_actual_days;
   public String s_eo_filter;
   public String s_eo_revision;
   public String s_message_error1;
   public String s_message_error2;
   public String s_message_type;
   public String s_message_answer;
   public String s_etops_check;
   public String s_override;
   public Date dt_birth_date;
   public Date dt_received_date;
   public Date shelf_life_expiration;
   public Integer l_pool_number;
   public String s_pool_type;
   //public TraxController w_win;
   public List<st_pn_control> pnControlList = new ArrayList<>();
   public List<StPn> nlaList = new ArrayList<>();
   public String s_company;
   public String s_average_cost;
   public String s_secondary_cost;
   public boolean is_kit_import;
}

