//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 11:18:07 AM EDT 
//


package trax.aero.outbound;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;




@XmlRootElement(name="MT_TRAX_I10_ACK_4111", namespace="http://singaporeair.com/mro/ESDTRAX")
@XmlAccessorType(XmlAccessType.FIELD)
public class MT_TRAX_I10_TRAX
{
	
	@XmlElement(name = "ORDER")
	 private ArrayList<Order> Order;

	    public ArrayList<Order> getOrder ()
	    {
	        return Order;
	    }

	    public void setOrder (ArrayList<Order> order)
	    {
	        this.Order = order;
	    }
	
	
	
	

	

	

	
}
